# Tier 1 functional tests for read_legofit_output / read_legofit_bootstrap
# Per at2-legofit-integration-pr-delta-test-plan.md.
#
# Each test exercises the reader on realistic inputs beyond the single
# ourex1 fixture used by unit tests. Fixtures live in tests/testthat/fixtures/.

# ---------------------------------------------------------------------------
# T1.2 — Coalescent unit vs scalar twoN modes both round trip without
# spurious legofit_param_mismatch informs.
# ---------------------------------------------------------------------------

test_that("T1.2: coalescent-unit (one=1) ourex1.legofit emits no spurious mismatch", {
  mismatch_fired <- FALSE
  withCallingHandlers(
    read_legofit_output(test_path("fixtures", "ourex1.legofit"),
                        graph = make_ourex1_graph()),
    legofit_param_mismatch = function(m) {
      mismatch_fired <<- TRUE
      tryInvokeRestart("muffleMessage")
    }
  )
  expect_false(mismatch_fired)
})

test_that("T1.2: scalar-twoN (shared=N) ourex1.legofit emits no spurious mismatch", {
  mismatch_fired <- FALSE
  withCallingHandlers(
    read_legofit_output(test_path("fixtures", "ourex1-twoN-scalar.legofit"),
                        graph = make_ourex1_graph()),
    legofit_param_mismatch = function(m) {
      mismatch_fired <<- TRUE
      tryInvokeRestart("muffleMessage")
    }
  )
  expect_false(mismatch_fired)
})

test_that("T1.2: scalar-twoN reader recognizes `shared` sentinel correctly", {
  result <- read_legofit_output(test_path("fixtures", "ourex1-twoN-scalar.legofit"),
                                graph = NULL)
  # Raw-param path: `shared` is classified as twoN_shared family
  shared_row <- result[result$name == "shared", ]
  expect_equal(nrow(shared_row), 1L)
  expect_equal(shared_row$family, "twoN_shared")
  expect_equal(shared_row$value, 1000)
})

# ---------------------------------------------------------------------------
# T1.5 — bootci.py output variants. Synthesize bootci files with optional
# `lbl` column and varying `--confidence` headers.
# ---------------------------------------------------------------------------

test_that("T1.5: bootci with -l label produces lbl column", {
  lbl_content <- c(
    "# bootci.py run at: 2026-05-21 10:00:00",
    "# input: /tmp/data.flat",
    "# confidence: 0.950",
    "       par             est             low            high             lbl",
    "      T_xy      0.50000000      0.46250000      0.53750000       fit_main",
    "     T_xyz      2.00000000      1.90625000      2.09375000       fit_main"
  )
  tmp <- tempfile(fileext = ".bootci")
  on.exit(unlink(tmp))
  writeLines(lbl_content, tmp)
  result <- read_legofit_bootstrap(tmp)
  expect_true("lbl" %in% names(result))
  expect_equal(result$lbl, c("fit_main", "fit_main"))
})

test_that("T1.5: bootci at --confidence 0.99 parses cleanly", {
  c99_content <- c(
    "# bootci.py run at: 2026-05-21 10:00:00",
    "# input: /tmp/data.flat",
    "# confidence: 0.990",
    "       par             est             low            high",
    "      T_xy      0.50000000      0.40000000      0.60000000",
    "     T_xyz      2.00000000      1.80000000      2.20000000"
  )
  tmp <- tempfile(fileext = ".bootci")
  on.exit(unlink(tmp))
  writeLines(c99_content, tmp)
  result <- read_legofit_bootstrap(tmp)
  expect_equal(nrow(result), 2L)
  expect_false("lbl" %in% names(result))
  # Wider bounds for 0.99 confidence
  xy <- result[result$parameter == "T_xy", ]
  expect_equal(xy$hi - xy$lo, 0.2, tolerance = 1e-6)
})

test_that("T1.5: bootci with both -l and --confidence 0.99 parses correctly", {
  both_content <- c(
    "# bootci.py run at: 2026-05-21 10:00:00",
    "# input: /tmp/data.flat",
    "# confidence: 0.990",
    "       par             est             low            high             lbl",
    "      T_xy      0.50000000      0.40000000      0.60000000           run1",
    "     T_xyz      2.00000000      1.80000000      2.20000000           run1"
  )
  tmp <- tempfile(fileext = ".bootci")
  on.exit(unlink(tmp))
  writeLines(both_content, tmp)
  result <- read_legofit_bootstrap(tmp)
  expect_true("lbl" %in% names(result))
  expect_equal(unique(result$lbl), "run1")
  expect_equal(nrow(result), 2L)
})

# ---------------------------------------------------------------------------
# T1.7 — finished_iterations convergence inform fires on a real
# underconverged fit (generated by capping legofit at -S 1 generation).
# ---------------------------------------------------------------------------

test_that("T1.7: legofit_fit_incomplete fires on real underconverged .legofit (graph= supplied)", {
  expect_message(
    read_legofit_output(test_path("fixtures", "ourex1-underconverged.legofit"),
                        graph = make_ourex1_graph()),
    class = "legofit_fit_incomplete"
  )
})

test_that("T1.7: legofit_fit_incomplete fires on real underconverged .legofit (graph=NULL)", {
  # Use a fresh frequency_id by deduping on path: T1.7-graph and T1.7-null share
  # the same fixture path, so the .frequency_id is the same — the second call
  # would be deduped. Use a different copy to give it a unique path.
  tmp <- tempfile(fileext = ".legofit")
  on.exit(unlink(tmp))
  file.copy(test_path("fixtures", "ourex1-underconverged.legofit"), tmp)
  expect_message(
    read_legofit_output(tmp, graph = NULL),
    class = "legofit_fit_incomplete"
  )
})

test_that("T1.7: fit_convergence attribute carries finished_iterations status", {
  result <- suppressMessages(read_legofit_output(
    test_path("fixtures", "ourex1-underconverged.legofit"),
    graph = make_ourex1_graph()
  ))
  conv <- attr(result, "fit_convergence")
  expect_equal(conv$status, "finished_iterations")
  expect_gt(conv$spread, 1e-4)   # spread is large because underconverged
})

# ---------------------------------------------------------------------------
# T1.4 — include_fixed = FALSE parity across coalescent-unit and scalar-twoN
# topologies. The free-fitted parameter set must be identical in both modes.
# ---------------------------------------------------------------------------

test_that("T1.4: include_fixed parity for coalescent-unit ourex1", {
  full     <- read_legofit_output(test_path("fixtures", "ourex1.legofit"),
                                  graph = NULL)
  no_fixed <- read_legofit_output(test_path("fixtures", "ourex1.legofit"),
                                  graph = NULL, include_fixed = FALSE)
  # The free-fitted subset must be identical
  full_free <- full[full$family != "twoN_one" &
                    !full$name %in% c("T_z", "T_x", "T_y"), c("name", "value")]
  expect_equal(no_fixed[, c("name", "value")], full_free,
               ignore_attr = TRUE)
})

test_that("T1.4: include_fixed parity for scalar-twoN ourex1", {
  full     <- read_legofit_output(test_path("fixtures", "ourex1-twoN-scalar.legofit"),
                                  graph = NULL)
  no_fixed <- read_legofit_output(test_path("fixtures", "ourex1-twoN-scalar.legofit"),
                                  graph = NULL, include_fixed = FALSE)
  full_free <- full[full$family != "twoN_shared" &
                    !full$name %in% c("T_z", "T_x", "T_y"), c("name", "value")]
  expect_equal(no_fixed[, c("name", "value")], full_free,
               ignore_attr = TRUE)
})

test_that("T1.4: include_fixed=FALSE emits no spurious mismatch on scalar twoN", {
  mismatch_fired <- FALSE
  withCallingHandlers(
    read_legofit_output(test_path("fixtures", "ourex1-twoN-scalar.legofit"),
                        graph = make_ourex1_graph(), include_fixed = FALSE),
    legofit_param_mismatch = function(m) {
      mismatch_fired <<- TRUE
      tryInvokeRestart("muffleMessage")
    }
  )
  expect_false(mismatch_fired)
})

# ---------------------------------------------------------------------------
# T1.8 — Performance bound. read_legofit_output on a 100-parameter
# synthetic .legofit completes in under 1 second.
# ---------------------------------------------------------------------------

test_that("T1.8: read_legofit_output handles a 100-parameter .legofit in under 1s", {
  skip_on_cran()
  # Synthesize a large .legofit with 50 fixed + 50 free params
  n <- 50
  free_lines  <- sprintf("     T_n%03d = %g", seq_len(n), runif(n, 0.1, 2))
  fixed_lines <- sprintf("       T_f%03d = 0", seq_len(n))
  one_line    <- "       one = 1"
  content <- c(
    "Initial parameter values",
    "Fixed:", fixed_lines, one_line,
    "Free:", free_lines,
    "DiffEv reached_goal. cost=1e-10 spread=1e-7",
    "Fitted parameter values",
    "Free:", free_lines
  )
  tmp <- tempfile(fileext = ".legofit")
  on.exit(unlink(tmp))
  writeLines(content, tmp)
  t <- system.time(suppressMessages(
    read_legofit_output(tmp, graph = NULL)
  ))[["elapsed"]]
  expect_lt(t, 1.0)
})

test_that("T1.8: parse_bootci_output handles a 100-row .bootci in under 1s", {
  skip_on_cran()
  n <- 100
  header <- "       par             est             low            high"
  data_rows <- sprintf("    T_n%03d   %.8f   %.8f   %.8f",
                       seq_len(n), runif(n), runif(n, 0, 0.5), runif(n, 0.5, 1))
  content <- c(
    "# bootci.py run at: 2026-05-21",
    "# confidence: 0.950",
    header, data_rows
  )
  t <- system.time(parse_bootci_output(content))[["elapsed"]]
  expect_lt(t, 1.0)
})

# ---------------------------------------------------------------------------
# T1.6 — Read rha20.legofit. Real 20-leaf topology with multi admixture.
# Generated by `legofit -S 1@100 -p 3` on legosim-simulated patterns
# (finished_iterations, wildly underconverged — that is the point: we are
# testing the reader, not LEGOFIT's optimizer).
# ---------------------------------------------------------------------------

test_that("T1.6: read_legofit_output parses rha20.legofit cleanly (graph=NULL)", {
  result <- suppressMessages(
    read_legofit_output(test_path("fixtures", "rha20.legofit"), graph = NULL)
  )
  # Should have 20+ params (17 free + some fixed)
  expect_gt(nrow(result), 17L)
  # All families classified (no "unknown" except possibly LEGOFIT-internal sentinels)
  expect_true(all(result$family %in%
    c("time", "twoN", "mixFrac", "admix_time", "twoN_one", "twoN_shared", "unknown")))
})

test_that("T1.6: rha20.legofit convergence is finished_iterations", {
  result <- suppressMessages(read_legofit_output(
    test_path("fixtures", "rha20.legofit"), graph = NULL
  ))
  conv <- attr(result, "fit_convergence")
  expect_equal(conv$status, "finished_iterations")
})

test_that("T1.6: rha20.legofit fires legofit_fit_incomplete inform", {
  # Use a fresh tempfile copy to get a unique .frequency_id key (the inform
  # is once-per-path; the other T1.6 tests already consumed the original path).
  tmp <- tempfile(fileext = ".legofit")
  on.exit(unlink(tmp))
  file.copy(test_path("fixtures", "rha20.legofit"), tmp)
  expect_message(
    read_legofit_output(tmp, graph = NULL),
    class = "legofit_fit_incomplete"
  )
})

# ---------------------------------------------------------------------------
# T1.3 — Multi admix .legofit parse. Three-leaf one-admix topology.
# Fixture multi-admix.legofit generated via:
#   legosim -i 5000 multi-admix.lgo > multi-admix.opf
#   legofit -t 2 -d 1e-3 multi-admix.lgo multi-admix.opf > multi-admix.legofit
# (deterministic threshold 1e-3, reached_goal in <30s).
# ---------------------------------------------------------------------------

test_that("T1.3: multi-admix.legofit parses with graph=NULL", {
  result <- suppressMessages(read_legofit_output(
    test_path("fixtures", "multi-admix.legofit"), graph = NULL
  ))
  expect_s3_class(result, "tbl_df")
  # Free fitted params: T_R, T_A, T_B, T_admix_m, m_m (5 params)
  expect_true(all(c("T_R", "T_A", "T_B", "T_admix_m", "m_m") %in% result$name))
  # Family classifications
  expect_equal(result$family[result$name == "T_admix_m"], "admix_time")
  expect_equal(result$family[result$name == "m_m"], "mixFrac")
})

test_that("T1.3: multi-admix.legofit with graph produces edge tibble with admix metadata", {
  result <- suppressMessages(read_legofit_output(
    test_path("fixtures", "multi-admix.legofit"),
    graph = make_multi_admix_graph()
  ))
  expect_true("admix_event_time" %in% names(result))
  expect_true("admix_prop"       %in% names(result))
  # Admix edges (A->m, B->m) should have admix_event_time populated
  admix_edges <- result[result$type == "admix", ]
  expect_true(nrow(admix_edges) == 2L)
  expect_true(all(!is.na(admix_edges$admix_event_time)))
  # Both admix edges share the same T_admix_m
  expect_equal(length(unique(admix_edges$admix_event_time)), 1L)
})

test_that("T1.3: multi-admix.legofit emits no spurious mismatch", {
  mismatch_fired <- FALSE
  withCallingHandlers(
    read_legofit_output(test_path("fixtures", "multi-admix.legofit"),
                        graph = make_multi_admix_graph()),
    legofit_param_mismatch = function(m) {
      mismatch_fired <<- TRUE
      tryInvokeRestart("muffleMessage")
    }
  )
  expect_false(mismatch_fired)
})

test_that("T1.3: multi-admix node_times attribute covers all nodes", {
  result <- suppressMessages(read_legofit_output(
    test_path("fixtures", "multi-admix.legofit"),
    graph = make_multi_admix_graph()
  ))
  nt <- attr(result, "node_times")
  # All graph nodes (R, A, B, x, y, m) should have entries
  expect_setequal(names(nt), c("R", "A", "B", "x", "y", "m"))
})

# ---------------------------------------------------------------------------
# T1.3 bootstrap variant — read multi-admix.bootci.
# Fixture produced via the T2.2 pipeline: 10 legosim replicates → 10
# legofit fits → flatfile.py → bootci.py.
# ---------------------------------------------------------------------------

test_that("T1.3-boot: multi-admix.bootci reader produces 5-row CI tibble", {
  result <- read_legofit_bootstrap(test_path("fixtures", "multi-admix.bootci"),
                                    graph = make_multi_admix_graph())
  expect_equal(nrow(result), 5L)
  expect_equal(names(result),
               c("parameter", "family", "point_estimate", "lo", "hi"))
  expect_setequal(result$parameter, c("T_R", "T_A", "T_B", "T_admix_m", "m_m"))
})

test_that("T1.3-boot: multi-admix bootstrap CI bounds bracket point estimate", {
  result <- read_legofit_bootstrap(test_path("fixtures", "multi-admix.bootci"),
                                    graph = make_multi_admix_graph())
  expect_true(all(result$lo <= result$point_estimate))
  expect_true(all(result$hi >= result$point_estimate))
})

test_that("T1.3-boot: family classification correct for admix params", {
  result <- read_legofit_bootstrap(test_path("fixtures", "multi-admix.bootci"))
  expect_equal(result$family[result$parameter == "T_admix_m"], "admix_time")
  expect_equal(result$family[result$parameter == "m_m"],       "mixFrac")
  expect_equal(result$family[result$parameter == "T_R"],       "time")
})
