<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Using admixtools in R • admixtools</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Using admixtools in R">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">admixtools</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/admixtools.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/plotting.html">Plotting</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
<form class="navbar-form navbar-right hidden-xs hidden-sm" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Using admixtools in R</h1>
            
      
      
      <div class="hidden name"><code>admixtools.Rmd</code></div>

    </div>

    
    
<p>For the examples below the following R packages need to be loaded.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(admixtools)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(magrittr)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(tidyverse)</a></code></pre></div>
<p><br></p>
<div id="qpadm" class="section level2">
<h2 class="hasAnchor">
<a href="#qpadm" class="anchor"></a>qpAdm</h2>
<p>If you have access to pre-computed f2-statistics, you use them to compute admixture weights. The following should work on O2.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">target =<span class="st"> 'Denisova.DG'</span></a>
<a class="sourceLine" id="cb2-2" data-line-number="2">left =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'Altai_Neanderthal.DG'</span>, <span class="st">'Vindija.DG'</span>)</a>
<a class="sourceLine" id="cb2-3" data-line-number="3">right =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'Chimp.REF'</span>, <span class="st">'Mbuti.DG'</span>, <span class="st">'Russia_Ust_Ishim.DG'</span>, <span class="st">'Switzerland_Bichon.SG'</span>)</a></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">f2_dir =<span class="st"> '/n/groups/reich/robert/projects/admixprograms/f2blocks_v41.1/'</span></a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="kw"><a href="../reference/qpadm.html">qpadm</a></span>(target, left, right, <span class="dt">f2_dir =</span> f2_dir, <span class="dt">fstscale =</span> <span class="fl">3.6</span>)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   target      left                 weight    se
##   &lt;chr&gt;       &lt;chr&gt;                 &lt;dbl&gt; &lt;dbl&gt;
## 1 Denisova.DG Altai_Neanderthal.DG   43.4  17.7
## 2 Denisova.DG Vindija.DG            -42.4  17.7</code></pre>
<div id="caveats" class="section level3">
<h3 class="hasAnchor">
<a href="#caveats" class="anchor"></a>Caveats</h3>
<p>This function only reports <code>qpAdm</code> admixture weights, and doesn’t determine the number of independent source populations. The <code>qpadm</code> function also hasn’t been tested as much as the <code>qpgraph</code> function, and the results are sometimes not very accurate, in particular when the weights are outside the range of [0, 1], like in this example.</p>
<p><br></p>
</div>
</div>
<div id="qpgraph" class="section level2">
<h2 class="hasAnchor">
<a href="#qpgraph" class="anchor"></a>qpGraph</h2>
<p>The f2-statistics can also be used to fit an admixture graph to the data.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">qpg_results =<span class="st"> </span><span class="kw"><a href="../reference/qpgraph.html">qpgraph</a></span>(graph1, <span class="dt">f2_dir =</span> f2_dir)</a></code></pre></div>
<p>Here, <code>graph1</code> is a specific graph included in this R package, but it can be any other graph in one of three formats.</p>
<ol style="list-style-type: decimal">
<li>An <a href="https://igraph.org/r/"><code>igraph</code></a> object.</li>
<li>A two column matrix of edges, where the first column is the source of each edge, and the second column is the target.</li>
<li>The location of a <code>qpGraph</code> graph file, which will be read and parsed.</li>
</ol>
<p>The only requirements for the input graph are that the graph is a valid admixture graph – a DAG with one outgroup edge connecting the root to a leaf node – and that f2-statistics exist for all leaf nodes. The first edge should go from the root to the outgroup.</p>
<p><br></p>
<p>The <code>qpgraph</code> output is a list with five items:</p>
<ol style="list-style-type: decimal">
<li>A data frame with estimated edge weights. This includes normal edges as well as admixture edges</li>
<li>The likelihood score. Smaller scores indicate a better fit</li>
<li>The estimated f2-statistics and standard errors for all population pairs</li>
<li>The estimated f3-statistics and standard errors for all population pairs with the outgroup</li>
<li>A data frame with details from the weight optimization, with one row per set of starting values</li>
</ol>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">qpg_results<span class="op">$</span>edges</a></code></pre></div>
<pre><code>## # A tibble: 27 x 5
##    from  to                   type   weight label
##    &lt;chr&gt; &lt;chr&gt;                &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1 R     Chimp.REF            edge  0.203    0.2 
##  2 R     N4N                  edge  0.203    0.2 
##  3 N0N   Altai_Neanderthal.DG edge  0.00766  0.01
##  4 N0N   N3N0                 edge  0.0293   0.03
##  5 N1N   N0N                  edge  0.234    0.23
##  6 N1N   N3N1                 edge  0.0982   0.1 
##  7 N2N0  N1N                  edge  0.106    0.11
##  8 N2N0  N3N6                 edge  0.0428   0.04
##  9 N2N1  Vindija.DG           edge  0        0   
## 10 N2N1  N2N3                 edge  0        0   
## # … with 17 more rows</code></pre>
<p><br></p>
<p>This works for any populations for which there are precomputed f2-statistics.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">allpops =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/list.files.html">list.dirs</a></span>(f2_dir, <span class="dt">full.names =</span> <span class="ot">FALSE</span>, <span class="dt">recursive =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb8-2" data-line-number="2">rand_pops =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/sample.html">sample</a></span>(allpops, <span class="dv">20</span>)</a>
<a class="sourceLine" id="cb8-3" data-line-number="3">rand_graph =<span class="st"> </span><span class="kw"><a href="../reference/random_admixturegraph.html">random_admixturegraph</a></span>(rand_pops, <span class="dt">numadmix =</span> <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb8-4" data-line-number="4">rand_results =<span class="st"> </span><span class="kw"><a href="../reference/qpgraph.html">qpgraph</a></span>(rand_graph, <span class="dt">f2_dir =</span> f2_dir, <span class="dt">fstscale =</span> <span class="fl">3.6</span>, <span class="dt">verbose =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<div id="caveats-1" class="section level3">
<h3 class="hasAnchor">
<a href="#caveats-1" class="anchor"></a>Caveats</h3>
<ul>
<li>A ‘fudge’ factor is added to the diagonal elements of the covariance matrix, to ensure that the matrix inversion is stable. This factor defaults to a relatively large value of 1e-3, to ensure that no error will be thrown in most cases. However, the original qpGraph uses 1e-5, which gives more accurate results in most cases. Increasing this factor seems to have a small effect on admixture weights and branch lengths, but a larger effect on the likelihood scores.</li>
<li>Write something about how missing data is treated and useallsnps YES/NO</li>
</ul>
<p><br></p>
</div>
</div>
<div id="compare-results-to-admixtools" class="section level2">
<h2 class="hasAnchor">
<a href="#compare-results-to-admixtools" class="anchor"></a>Compare results to AdmixTools</h2>
<p>There are wrapper function which call the origial <code>AdmixTools</code> programs and read the results. This can be used to check if the results of <code>qpgraph</code> are correct.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">qpgraph_bin =<span class="st"> '/home/np29/o2bin/qpGraph'</span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2">qpadm_bin =<span class="st"> '/home/np29/o2bin/qpAdm'</span></a>
<a class="sourceLine" id="cb9-3" data-line-number="3">env =<span class="st"> 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/n/app/openblas/0.2.19/lib/:/n/app/gsl/2.3/lib/;'</span></a>
<a class="sourceLine" id="cb9-4" data-line-number="4"><span class="co">#prefix = '/n/groups/reich/DAVID/V41/V41.1/v41.1'</span></a>
<a class="sourceLine" id="cb9-5" data-line-number="5">prefix =<span class="st"> '/n/groups/reich/robert/projects/admixprograms/v41.0_small'</span></a>
<a class="sourceLine" id="cb9-6" data-line-number="6"></a>
<a class="sourceLine" id="cb9-7" data-line-number="7"><span class="kw"><a href="../reference/qpadm_wrapper.html">qpadm_wrapper</a></span>(target, left, right, <span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(env, qpadm_bin), prefix)</a>
<a class="sourceLine" id="cb9-8" data-line-number="8">qpgraph_ref_results =<span class="st"> </span><span class="kw"><a href="../reference/qpgraph_wrapper2.html">qpgraph_wrapper2</a></span>(graph1, <span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(env, qpgraph_bin), prefix)</a></code></pre></div>
<p><strong>Unless <code>outdir</code> is specified, calling these wrapper functions may overwrite files in the working directory!</strong></p>
<p><br></p>
<p>The following function makes it easy to compare qpGraph results.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="kw"><a href="../reference/plot_comparison.html">plot_comparison</a></span>(qpg_results, qpgraph_ref_results)</a></code></pre></div>
<p><img src="admixtools_files/figure-html/unnamed-chunk-10-1.png" width="700"><br></p>
<p>Currently the precomputed f2-statistics are not scaled, which it why it is necessary to set <code>fstscale</code> to <code>3.6</code> to get matching results. Without that scaling, the absolute values may differ, but the relative values should still be ok.</p>
<p>There are at least a few examples where the results seem to be approximately correct. Please let me know if you find examples where the results are different!</p>
<p><br></p>
</div>
<div id="compute-f2-statistics" class="section level2">
<h2 class="hasAnchor">
<a href="#compute-f2-statistics" class="anchor"></a>Compute f2-statistics</h2>
<p>If you’re not on O2, or want use different f-statistics, you first have to compute allele frequencies for your populations of interest from data in <code>packedancestrymap</code> format.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">pops =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'Denisova.DG'</span>,</a>
<a class="sourceLine" id="cb11-2" data-line-number="2">         <span class="st">'Altai_Neanderthal.DG'</span>,</a>
<a class="sourceLine" id="cb11-3" data-line-number="3">         <span class="st">'Vindija.DG'</span>,</a>
<a class="sourceLine" id="cb11-4" data-line-number="4">         <span class="st">'Chimp.REF'</span>,</a>
<a class="sourceLine" id="cb11-5" data-line-number="5">         <span class="st">'Mbuti.DG'</span>,</a>
<a class="sourceLine" id="cb11-6" data-line-number="6">         <span class="st">'Russia_Ust_Ishim.DG'</span>,</a>
<a class="sourceLine" id="cb11-7" data-line-number="7">         <span class="st">'Switzerland_Bichon.SG'</span>)</a>
<a class="sourceLine" id="cb11-8" data-line-number="8"></a>
<a class="sourceLine" id="cb11-9" data-line-number="9">afdat =<span class="st"> </span><span class="kw"><a href="../reference/packedancestrymap_to_aftable.html">packedancestrymap_to_aftable</a></span>(prefix, pops, <span class="dt">na.action=</span><span class="st">'remove'</span>)</a></code></pre></div>
<p><br></p>
<p>We also need to keep track of the number of samples in each population.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">indfile =<span class="st"> </span><span class="kw">read_table2</span>(<span class="kw"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span>(prefix, <span class="st">'.ind'</span>), <span class="dt">col_names =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">'iid'</span>, <span class="st">'sex'</span>, <span class="st">'group'</span>))</a>
<a class="sourceLine" id="cb12-2" data-line-number="2">popcounts =<span class="st"> </span>indfile <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span>(group <span class="op">%in%</span><span class="st"> </span>pops) <span class="op">%$%</span><span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/table.html">table</a></span>(group)</a></code></pre></div>
<p><br></p>
<p>Reading the genotype data is rather slow, so it’s a good idea to save the output.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/save.html">save</a></span>(afdat, popcounts, <span class="dt">file =</span> <span class="st">'my_afdat.RData'</span>)</a></code></pre></div>
<p><br></p>
<p>Then you can use these allele frequencies to compute block-jackknife estimates of f2-statistics.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="co"># This assigns each SNP to a jackknife block, based on a 5 centimorgan genomic distance</span></a>
<a class="sourceLine" id="cb14-2" data-line-number="2">block_lengths =<span class="st"> </span><span class="kw"><a href="../reference/get_block_lengths.html">get_block_lengths</a></span>(afdat)</a></code></pre></div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="co"># This computes the f2-statistics. By default, f2 is scaled by a factor of 3.6 which</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2"><span class="co"># makes it approximately equal to Fst. In contrast, the f2-statistics in</span></a>
<a class="sourceLine" id="cb15-3" data-line-number="3"><span class="co"># /n/groups/reich/robert/projects/admixprograms/f2blocks_v41.1/ are not scaled,</span></a>
<a class="sourceLine" id="cb15-4" data-line-number="4"><span class="co"># and so the scaling is applied in the qpadm and qpgraph functions when using those f2-statistics.</span></a>
<a class="sourceLine" id="cb15-5" data-line-number="5">f2_blocks =<span class="st"> </span><span class="kw"><a href="../reference/afs_to_f2_blocks.html">afs_to_f2_blocks</a></span>(<span class="dt">afs =</span> afdat, <span class="dt">popcounts =</span> popcounts, <span class="dt">block_lengths =</span> block_lengths)</a></code></pre></div>
<p><br></p>
<p>This also takes a while, so you should also save it.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/save.html">save</a></span>(f2_blocks, block_lengths, <span class="dt">file =</span> <span class="st">'my_f2_blocks.RData'</span>)</a></code></pre></div>
<p><br></p>
<p>Now we can use this to compute admixture weights.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw"><a href="../reference/qpadm.html">qpadm</a></span>(target, left, right, f2_blocks, block_lengths)</a></code></pre></div>
<p><br></p>
<p>We can use the same f2-statistics as input for qpGraph.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1">qpg_results =<span class="st"> </span><span class="kw"><a href="../reference/qpgraph.html">qpgraph</a></span>(graph1, f2_blocks, block_lengths)</a></code></pre></div>
<p><br></p>
</div>
<div id="plot-qpgraph-results" class="section level2">
<h2 class="hasAnchor">
<a href="#plot-qpgraph-results" class="anchor"></a>Plot qpgraph results</h2>
<p>This plots the <code>qpgraph</code> results.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw"><a href="../reference/plot_graph.html">plot_graph</a></span>(qpg_results<span class="op">$</span>edges)</a></code></pre></div>
<p><img src="admixtools_files/figure-html/unnamed-chunk-19-1.png" width="864" style="display: block; margin: auto;"></p>
<p><br></p>
</div>
<div id="find-graphs-with-good-fits" class="section level2">
<h2 class="hasAnchor">
<a href="#find-graphs-with-good-fits" class="anchor"></a>Find graphs with good fits</h2>
<p>Since evaluating one graph doesn’t take long once the f-statistics are pre-computed, we can evaluate many graphs and find graph topologies with good fits.</p>
<p><br></p>
<p>In order for that to be as fast as possible, we can precompute and reuse f3-statistics and the inverse of the f3-statistic covariance matrix.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">precomp =<span class="st"> </span><span class="kw"><a href="../reference/qpgraph_precompute_f3.html">qpgraph_precompute_f3</a></span>(pops, <span class="dt">f2_dir =</span> f2_dir, <span class="dt">fstscale =</span> <span class="fl">3.6</span>)</a>
<a class="sourceLine" id="cb20-2" data-line-number="2">f3_jest =<span class="st"> </span>precomp[[<span class="dv">1</span>]]</a>
<a class="sourceLine" id="cb20-3" data-line-number="3">ppinv =<span class="st"> </span>precomp[[<span class="dv">2</span>]]</a></code></pre></div>
<p><br></p>
<p>The function <code>optimize_admixturegraph</code> generates and evaluates <code>numgraphs</code> admixture graphs in <code>numgen</code> iterations across <code>numrep</code> independent repeats to find well fitting admixture graphs.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">opt_results =<span class="st"> </span><span class="kw"><a href="../reference/optimize_admixturegraph.html">optimize_admixturegraph</a></span>(pops, f3_jest, ppinv,</a>
<a class="sourceLine" id="cb21-2" data-line-number="2">                                      <span class="dt">numrep =</span> <span class="dv">200</span>, <span class="dt">numgraphs =</span> <span class="dv">100</span>, <span class="dt">numgen =</span> <span class="dv">20</span>,</a>
<a class="sourceLine" id="cb21-3" data-line-number="3">                                      <span class="dt">numsel =</span> <span class="dv">5</span>, <span class="dt">numadmix =</span> <span class="dv">3</span>)</a></code></pre></div>
<p><br></p>
<p>Once that is done, the following commands will extract the best fitting model overall, and the best fitting model from each independent repeat.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">winner =<span class="st"> </span>opt_results <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">top_n</span>(<span class="dv">1</span>, <span class="op">-</span><span class="kw"><a href="https://rdrr.io/r/base/jitter.html">jitter</a></span>(score))</a>
<a class="sourceLine" id="cb22-2" data-line-number="2">winners =<span class="st"> </span>opt_results <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(run) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">top_n</span>(<span class="dv">1</span>, <span class="op">-</span><span class="kw"><a href="https://rdrr.io/r/base/jitter.html">jitter</a></span>(score)) <span class="op">%&gt;%</span><span class="st"> </span>ungroup</a></code></pre></div>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">winner<span class="op">$</span>score[[<span class="dv">1</span>]]</a></code></pre></div>
<pre><code>## [1] 4.009599</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw"><a href="../reference/plot_graph.html">plot_graph</a></span>(winner<span class="op">$</span>edges[[<span class="dv">1</span>]], <span class="dt">fix =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="admixtools_files/figure-html/unnamed-chunk-23-1.png" width="864" style="display: block; margin: auto;"><br></p>
</div>
<div id="parallelization" class="section level2">
<h2 class="hasAnchor">
<a href="#parallelization" class="anchor"></a>Parallelization</h2>
<p>Depending on the input parameters, <code>optimize_admixturegraph</code> can take a long time to run. With the parameters above, 420,000 admixture graphs (200 * 100 * (20+1)) will be generated and evaluated. Thanks to the function <a href="https://www.rdocumentation.org/packages/furrr/versions/0.1.0/topics/future_map"><code>future_map</code></a> from the <a href="https://github.com/DavisVaughan/furrr"><code>furrr</code></a> package, this can be sped up by parallelizing across the independent repeats. The function <a href="https://www.rdocumentation.org/packages/future/versions/1.15.1/topics/plan"><code><a href="https://rdrr.io/pkg/future/man/plan.html">future::plan</a></code></a> can be called to specify the details of the parallelization. This can be used to parallelize across CPU cores or across nodes on a compute cluster.</p>
<p>Setting it up like this will make it run multithreaded:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1">future<span class="op">::</span><span class="kw"><a href="https://rdrr.io/pkg/future/man/plan.html">plan</a></span>(<span class="st">'multiprocess'</span>)</a></code></pre></div>
<p><br></p>
<p>On the O2 cluster, the following command will set up parallelization across compute nodes.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">future<span class="op">::</span><span class="kw"><a href="https://rdrr.io/pkg/future/man/plan.html">plan</a></span>(<span class="kw">tweak</span>(batchtools_slurm, <span class="dt">workers =</span> <span class="dv">50</span>,</a>
<a class="sourceLine" id="cb27-2" data-line-number="2">                   <span class="dt">resources=</span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">ncpus =</span> <span class="dv">1</span>, <span class="dt">memory =</span> <span class="dv">1024</span>,</a>
<a class="sourceLine" id="cb27-3" data-line-number="3">                                  <span class="dt">walltime =</span> <span class="dv">10</span><span class="op">*</span><span class="dv">60</span><span class="op">*</span><span class="dv">60</span>, <span class="dt">partition =</span> <span class="st">'short'</span>)))</a></code></pre></div>
<p>This specifies that up to 50 jobs should be run at a time, with each one requesting one CPU, 1024 MB of memory, and 10 hours on the <code>short</code> partition.</p>
<p>This requires the R package <code>future.batchtools</code> and a batchtools template file in the working directory, such as this one: <code>/n/groups/reich/robert/projects/admixprograms/batchtools.slurm.tmpl</code>.</p>
<p>After that, the <code>optimize_admixturegraph</code> function will submit each of the 200 repeats as a separate job.</p>
<p>As it will still take a while for this to finish, it is a good idea to submit this as one job which calls an R script. That R script will in turn spawn 200 new jobs and wait for them to finish and return their results.</p>
<p>First, the input should be saved to a file.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/save.html">save</a></span>(pops, f3_jest, ppinv, <span class="dt">file =</span> <span class="st">'qpgraph_input.RData'</span>)</a></code></pre></div>
<p>The R script could then look like this.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(admixtools)</a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(future.batchtools)</a>
<a class="sourceLine" id="cb29-3" data-line-number="3"></a>
<a class="sourceLine" id="cb29-4" data-line-number="4"><span class="kw"><a href="https://rdrr.io/r/base/load.html">load</a></span>(<span class="st">'qpgraph_input.RData'</span>)</a>
<a class="sourceLine" id="cb29-5" data-line-number="5"></a>
<a class="sourceLine" id="cb29-6" data-line-number="6">future<span class="op">::</span><span class="kw"><a href="https://rdrr.io/pkg/future/man/plan.html">plan</a></span>(<span class="kw">tweak</span>(batchtools_slurm, <span class="dt">workers=</span><span class="dv">50</span>,</a>
<a class="sourceLine" id="cb29-7" data-line-number="7">                   <span class="dt">resources=</span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">ncpus =</span> <span class="dv">1</span>, <span class="dt">memory=</span><span class="dv">1024</span>,</a>
<a class="sourceLine" id="cb29-8" data-line-number="8">                                  <span class="dt">walltime=</span><span class="dv">10</span><span class="op">*</span><span class="dv">60</span><span class="op">*</span><span class="dv">60</span>, <span class="dt">partition=</span><span class="st">'short'</span>)))</a>
<a class="sourceLine" id="cb29-9" data-line-number="9"></a>
<a class="sourceLine" id="cb29-10" data-line-number="10">opt_results =<span class="st"> </span><span class="kw"><a href="../reference/optimize_admixturegraph.html">optimize_admixturegraph</a></span>(pops, <span class="dt">outpop =</span> pops[<span class="dv">1</span>],</a>
<a class="sourceLine" id="cb29-11" data-line-number="11">                                      f3_jest, ppinv, <span class="dt">numrep =</span> <span class="dv">200</span>,</a>
<a class="sourceLine" id="cb29-12" data-line-number="12">                                      <span class="dt">numgen =</span> <span class="dv">20</span>, <span class="dt">numgraphs =</span> <span class="dv">100</span>,</a>
<a class="sourceLine" id="cb29-13" data-line-number="13">                                      <span class="dt">numadmix =</span> <span class="dv">3</span>, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb29-14" data-line-number="14"></a>
<a class="sourceLine" id="cb29-15" data-line-number="15"><span class="kw"><a href="https://rdrr.io/r/base/save.html">save</a></span>(opt_results, <span class="dt">file=</span><span class="st">'opt_results.RData'</span>)</a></code></pre></div>
<p>It could be in a file called <code>opt_graphs.Rscript</code> and be run like this, or submitted as a job.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1">Rscript opt_graphs.Rscript</a></code></pre></div>
<p><br></p>
</div>
<div id="summarize-graphs" class="section level2">
<h2 class="hasAnchor">
<a href="#summarize-graphs" class="anchor"></a>Summarize graphs</h2>
<p>For any set of populations there may be many graphs which can explain the data about equally well. The following function attempts to summarize a set of graphs by counting how often each population triple occurs in which configuration across all graphs.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1">trip =<span class="st"> </span><span class="kw"><a href="../reference/summarize_triples.html">summarize_triples</a></span>(winners)</a></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1">trip <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="op">-</span>clade) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 14
##   name1 name2 name3 numgraphs   x13   x23   x31   x32 clade   x12   x21 toptopo
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;  
## 1 Russ… Swit… Deni…       200 0.005 0.245 0.505  0.38 0.345  0.88 0.505 011111 
## # … with 2 more variables: toptopocnt &lt;int&gt;, topos &lt;list&gt;</code></pre>
<p>The output for this population triple (1: <code>Rus</code>, 2: <code>Swi</code>, 3: <code>Den</code>) can be read like this:</p>
<ul>
<li>
<code>numgraphs</code>: 200 graphs were compared</li>
<li>
<code>clade</code>: In 34.5% of all graphs <code>Rus</code> and <code>Swi</code> form a clade with respect to <code>Den</code>
</li>
<li>
<code>x13</code>: In 0.5% of all graphs <code>Rus</code> is closer to <code>Den</code> than <code>Swi</code> is to <code>Den</code>, with ancestors of <code>Rus</code> admixing into <code>Den</code>
</li>
<li>
<code>x31</code>: In 50.5% of all graphs <code>Rus</code> is closer to <code>Den</code> than <code>Swi</code> is to <code>Den</code>, with ancestors of <code>Den</code> admixing into <code>Rus</code>
</li>
<li>
<code>x23</code>: In 24.5% of all graphs <code>Swi</code> is closer to <code>Den</code> than <code>Rus</code> is to <code>Den</code>, with ancestors of <code>Swi</code> admixing into <code>Den</code>
</li>
<li>
<code>x32</code>: In 38.0% of all graphs <code>Swi</code> is closer to <code>Den</code> than <code>Rus</code> is to <code>Den</code>, with ancestors of <code>Den</code> admixing into <code>Swi</code>
</li>
<li>
<code>toptopo</code>: The most common topology for this triple across all graphs. <code>011111</code> specifies a topology where condition <code>x13</code> is not satisfied, but conditions <code>x23</code>, <code>x31</code>, <code>x32</code>, <code>x12</code>, and <code>x21</code> are satisfied. A topology starting with <code>0000</code> is one where the first two populations form a clade.</li>
<li>
<code>toptopocnt</code>: The number of times <code>toptopo</code> was observed</li>
<li>
<code>topos</code>: The number of times each topology was observed</li>
</ul>
<p><br></p>
</div>
<div id="find-valid-qpadm-models" class="section level2">
<h2 class="hasAnchor">
<a href="#find-valid-qpadm-models" class="anchor"></a>Find valid qpAdm models</h2>
<p>Every admixture graph maps to a specific set of valid qpAdm models. The function <code>qpadm_models</code> lists all valid qpAdm models for a graph. Models which are contained within larger valid models are not shown. The number of valid qpAdm models can be very large for big graphs, so you should only run this on small graphs.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">mygraph =<span class="st"> </span>winners <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">6</span>) <span class="op">%$%</span><span class="st"> </span>igraph <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pluck</span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb34-2" data-line-number="2"><span class="kw"><a href="../reference/plot_graph.html">plot_graph</a></span>(mygraph)</a></code></pre></div>
<p><img src="admixtools_files/figure-html/unnamed-chunk-31-1.png" width="864" style="display: block; margin: auto;"></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="kw"><a href="../reference/qpadm_models.html">qpadm_models</a></span>(mygraph, <span class="dt">add_outgroup =</span> <span class="ot">TRUE</span>, <span class="dt">nested =</span> <span class="ot">FALSE</span>, <span class="dt">abbr =</span> <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   target left    right      
##   &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;      
## 1 Den    Alt,Mbu Chi,Rus,Swi
## 2 Den    Alt,Vin Chi,Rus,Swi
## 3 Den    Mbu,Vin Chi,Rus,Swi</code></pre>
<p>The only qpAdm models which are valid under this graph have <code>Den</code> as target and <code>Chi</code>, <code>Rus</code>, and <code>Swi</code> as right populations.</p>
<p>Valid qpAdm models need to satisfy the following criteria:</p>
<ul>
<li>There have to be more right populations than left populations</li>
<li>The left populations should not form a clade with respect to any right population. This means that a qpgraph outgroup is not an informative right population, but it can be included anyway, with <code>add_outgroup</code>.</li>
<li>Each set of left populations which forms a source for the target population has to form a clade with target at the exclusion of each right population. (Note: Check if that’s correct and if it can be stated in a better way.)</li>
</ul>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#qpadm">qpAdm</a></li>
      <li><a href="#qpgraph">qpGraph</a></li>
      <li><a href="#compare-results-to-admixtools">Compare results to AdmixTools</a></li>
      <li><a href="#compute-f2-statistics">Compute f2-statistics</a></li>
      <li><a href="#plot-qpgraph-results">Plot qpgraph results</a></li>
      <li><a href="#find-graphs-with-good-fits">Find graphs with good fits</a></li>
      <li><a href="#parallelization">Parallelization</a></li>
      <li><a href="#summarize-graphs">Summarize graphs</a></li>
      <li><a href="#find-valid-qpadm-models">Find valid qpAdm models</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Robert Maier, Nick Patterson.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script><script>
  docsearch({
    
    
    apiKey: '',
    indexName: 'bayesplot',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
