#' @import dplyr
#' @import readr
#' @import purrr
#' @import tidyr
#' @import stringr
#' @import ggplot2
# @import utils
#' @importFrom Rcpp sourceCpp
#' @importFrom magrittr set_colnames set_rownames "%$%" "%<>%"
#' @importFrom abind abind
#' @importFrom crayon blue red green bold italic
#' @importFrom foreach foreach "%dopar%"
#' @importFrom tibble as_tibble deframe enframe add_column rownames_to_column
#' @importFrom grDevices colorRampPalette heat.colors rgb
#' @importFrom graphics arrows axis lines mtext rect text
#' @importFrom stats cancor prcomp rnorm t.test
#' @importFrom utils read.table
# @importFrom stats na.omit setNames runif
#' @importFrom igraph V E neighbors subcomponent degree incident_edges all_simple_paths distances
#' graph_from_edgelist as_edgelist shortest_paths adjacent_vertices is.dag as_ids add_vertices delete_vertices
#' add_edges delete_edges difference set_vertex_attr
#' @useDynLib admixtools

TRUE

#' Tools for inferring demographic history from genetic data
#'
#' admixtools is a collection of several programs for calculating f-statistics
#' and using them to make inferences about demographic history from genetic data
#' Aside from the core functions \code{\link{qp3pop}}, \code{\link{qpdstat}}, \code{\link{qpadm}},
#' and \code{\link{qpgraph}}, there are also wrapper functions and parsing functions around the original
#' ADMIXTOOLS software, as well as functions to read genotype files and precompute the data necessary
#' to quickly compute f statistics.
#'
#' @author Robert Maier \email{robertmaier@@gmx.net}
#' @author Nick Patterson
#'
#' @references Patterson, N. et al. (2012) \emph{Ancient admixture in human history.} Genetics
#'
#' @seealso
#' \url{https://uqrmaie1.github.io/admixtools/index.html}
#'
#' @docType package
#' @name admixtools
NULL


#' Blocked f2-statistics for 7 populations
#'
#' @format A 3d array with populations along the first two dimensions,
#'         and SNP blocks along the 3rd dimension
"example_f2_blocks"

#' Admixture graph for 7 populations
#'
#' @format A two column matrix where each row represents one edge
"example_graph"

#' Admixture graph for 7 populations
#'
#' @format An `igraph` object
"example_igraph"

#' Data frame with one fitted admixture graph
#'
#' @format A data frame with a fitted admixture graph, generated by `find_graphs_old`
"example_opt"

#' Data frame with population triples
#'
#' @format A data frame with population triples, generated by `summarize_triples`
"example_triples"

#' Data frame with sample annotations
#'
#' @format A data frame with sample annotations
"example_anno"

#' example_graph fitted using qpGraph
#'
#' @format A list with parsed qpGraph output
"example_qpgraph_ref_results"

#' Simulated f2-statistics for 5 populations
#'
#' @format A 3d array of f2-statistics computed from msprime simulation output,
#'         with populations along the first two dimensions and SNP blocks along the 3rd
"example_f2sim1"


.onUnload = function (libpath) {
  # Don't unload the shared object while the OpenMP at-fork handler is live:
  # pthread_atfork handlers can't be removed, so unmapping the image would
  # dangle the handler and crash the next fork() (e.g. plan(multicore)). The
  # accessor returns FALSE on non-OpenMP builds, where unloading is fine.
  # Consequence for development: on an OpenMP build the .so stays mapped for the
  # session, so after recompiling you must restart R (not just reload) to pick
  # up the new build.
  active = tryCatch(admixtools_omp_atfork_active_(), error = function(e) FALSE)
  if (!isTRUE(active)) library.dynam.unload("admixtools", libpath)
}
