# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_plink_afs_cpp <- function(bedfile, indvec, indvec2, verbose) {
    .Call('_admixtools_read_plink_afs_cpp', PACKAGE = 'admixtools', bedfile, indvec, indvec2, verbose)
}

cpp_opt_A <- function(B, xvec, qinv, nr, fudge) {
    .Call('_admixtools_cpp_opt_A', PACKAGE = 'admixtools', B, xvec, qinv, nr, fudge)
}

cpp_opt_B <- function(A, xvec, qinv, nc, fudge) {
    .Call('_admixtools_cpp_opt_B', PACKAGE = 'admixtools', A, xvec, qinv, nc, fudge)
}

cpp_qpadm_weights <- function(xmat, qinv, rnk, fudge = 0.0001, iterations = 20L) {
    .Call('_admixtools_cpp_qpadm_weights', PACKAGE = 'admixtools', xmat, qinv, rnk, fudge, iterations)
}

cpp_get_weights_covariance <- function(f4_blocks, qinv, fudge = 0.0001) {
    .Call('_admixtools_cpp_get_weights_covariance', PACKAGE = 'admixtools', f4_blocks, qinv, fudge)
}

cpp_opt_edge_lengths <- function(ppwts_2d, ppinv, f3_jest, qpsolve) {
    .Call('_admixtools_cpp_opt_edge_lengths', PACKAGE = 'admixtools', ppwts_2d, ppinv, f3_jest, qpsolve)
}

cpp_fill_pwts <- function(pwts, weights, path_edge_table, path_admixedge_table, numpaths) {
    .Call('_admixtools_cpp_fill_pwts', PACKAGE = 'admixtools', pwts, weights, path_edge_table, path_admixedge_table, numpaths)
}

cpp_optimweightsfun <- function(weights, args) {
    .Call('_admixtools_cpp_optimweightsfun', PACKAGE = 'admixtools', weights, args)
}

