# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_opt_A <- function(B, xmat, qinv, fudge) {
    .Call('_admixtools_cpp_opt_A', PACKAGE = 'admixtools', B, xmat, qinv, fudge)
}

cpp_opt_B <- function(A, xmat, qinv, fudge) {
    .Call('_admixtools_cpp_opt_B', PACKAGE = 'admixtools', A, xmat, qinv, fudge)
}

cpp_qpadm_weights <- function(xmat, qinv, rnk, fudge = 0.0001, iterations = 20L) {
    .Call('_admixtools_cpp_qpadm_weights', PACKAGE = 'admixtools', xmat, qinv, rnk, fudge, iterations)
}

cpp_get_weights_covariance <- function(f4_blocks, qinv, fudge = 0.0001) {
    .Call('_admixtools_cpp_get_weights_covariance', PACKAGE = 'admixtools', f4_blocks, qinv, fudge)
}

cpp_opt_edge_lengths <- function(ppwts_2d, ppinv, f3_jest, qpsolve) {
    .Call('_admixtools_cpp_opt_edge_lengths', PACKAGE = 'admixtools', ppwts_2d, ppinv, f3_jest, qpsolve)
}

cpp_fill_pwts <- function(pwts, weights, path_edge_table, path_admixedge_table, numpaths) {
    invisible(.Call('_admixtools_cpp_fill_pwts', PACKAGE = 'admixtools', pwts, weights, path_edge_table, path_admixedge_table, numpaths))
}

cpp_optimweightsfun <- function(weights, args) {
    .Call('_admixtools_cpp_optimweightsfun', PACKAGE = 'admixtools', weights, args)
}

cpp_lbfgsb <- function(weights, pwts, ppinv, f3_jest, path_edge_table, path_admixedge_table, numpaths, qpsolve) {
    .Call('_admixtools_cpp_lbfgsb', PACKAGE = 'admixtools', weights, pwts, ppinv, f3_jest, path_edge_table, path_admixedge_table, numpaths, qpsolve)
}

