# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_aftable_to_dstatnum <- function(aftable, p1, p2, p3, p4) {
    .Call('_admixtools_cpp_aftable_to_dstatnum', PACKAGE = 'admixtools', aftable, p1, p2, p3, p4)
}

cpp_aftable_to_dstatden <- function(aftable, p1, p2, p3, p4) {
    .Call('_admixtools_cpp_aftable_to_dstatden', PACKAGE = 'admixtools', aftable, p1, p2, p3, p4)
}

cpp_opt_A <- function(B, xvec, qinv, nr, fudge) {
    .Call('_admixtools_cpp_opt_A', PACKAGE = 'admixtools', B, xvec, qinv, nr, fudge)
}

cpp_opt_B <- function(A, xvec, qinv, nc, fudge) {
    .Call('_admixtools_cpp_opt_B', PACKAGE = 'admixtools', A, xvec, qinv, nc, fudge)
}

cpp_qpadm_weights <- function(xmat, qinv, rnk, fudge = 0.0001, iterations = 20L, constrained = FALSE, qpsolve = NULL) {
    .Call('_admixtools_cpp_qpadm_weights', PACKAGE = 'admixtools', xmat, qinv, rnk, fudge, iterations, constrained, qpsolve)
}

cpp_get_weights_covariance <- function(f4_lo, qinv, block_lengths, fudge = 0.0001, boot = 0L, constrained = FALSE, qpsolve = NULL) {
    .Call('_admixtools_cpp_get_weights_covariance', PACKAGE = 'admixtools', f4_lo, qinv, block_lengths, fudge, boot, constrained, qpsolve)
}

cpp_is_polymorphic <- function(geno) {
    .Call('_admixtools_cpp_is_polymorphic', PACKAGE = 'admixtools', geno)
}

cpp_opt_edge_lengths <- function(ppwts_2d, ppinv, f3_est, qpsolve, lower, upper, fudge) {
    .Call('_admixtools_cpp_opt_edge_lengths', PACKAGE = 'admixtools', ppwts_2d, ppinv, f3_est, qpsolve, lower, upper, fudge)
}

cpp_fill_pwts <- function(pwts, weights, path_edge_table, path_admixedge_table, numpaths) {
    .Call('_admixtools_cpp_fill_pwts', PACKAGE = 'admixtools', pwts, weights, path_edge_table, path_admixedge_table, numpaths)
}

cpp_optimweightsfun <- function(weights, args) {
    .Call('_admixtools_cpp_optimweightsfun', PACKAGE = 'admixtools', weights, args)
}

cpp_get_pairindex <- function(perm) {
    .Call('_admixtools_cpp_get_pairindex', PACKAGE = 'admixtools', perm)
}

cpp_read_packedancestrymap <- function(genofile, nsnp, nind, indvec, first, last, transpose = FALSE, verbose = TRUE) {
    .Call('_admixtools_cpp_read_packedancestrymap', PACKAGE = 'admixtools', genofile, nsnp, nind, indvec, first, last, transpose, verbose)
}

cpp_packedancestrymap_to_aftable <- function(genofile, nsnp, nind, indvec, first, last, adjust_pseudohaploid, transpose, verbose) {
    .Call('_admixtools_cpp_packedancestrymap_to_aftable', PACKAGE = 'admixtools', genofile, nsnp, nind, indvec, first, last, adjust_pseudohaploid, transpose, verbose)
}

cpp_read_plink_afs <- function(bedfile, indvec, indvec2, adjust_pseudohaploid, verbose) {
    .Call('_admixtools_cpp_read_plink_afs', PACKAGE = 'admixtools', bedfile, indvec, indvec2, adjust_pseudohaploid, verbose)
}

cpp_get_block_lengths <- function(chr, pos, dist = 0.05) {
    .Call('_admixtools_cpp_get_block_lengths', PACKAGE = 'admixtools', chr, pos, dist)
}

cpp_jack_vec_stats <- function(loo_vec, block_lengths) {
    .Call('_admixtools_cpp_jack_vec_stats', PACKAGE = 'admixtools', loo_vec, block_lengths)
}

cpp_outer_array_mul <- function(m1, m2) {
    .Call('_admixtools_cpp_outer_array_mul', PACKAGE = 'admixtools', m1, m2)
}

cpp_outer_array_plus <- function(m1, m2) {
    .Call('_admixtools_cpp_outer_array_plus', PACKAGE = 'admixtools', m1, m2)
}

cpp_outer_array_minus <- function(m1, m2) {
    .Call('_admixtools_cpp_outer_array_minus', PACKAGE = 'admixtools', m1, m2)
}

cpp_mats_to_f2_arr <- function(afmat1, afmat2, countmat1, countmat2) {
    .Call('_admixtools_cpp_mats_to_f2_arr', PACKAGE = 'admixtools', afmat1, afmat2, countmat1, countmat2)
}

